version: 2
updates:
  # Mvn dependencies
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
