version: "3.7"
services:

  #############################################################################################
  ###                           Document Distribution Webservice                            ###
  #############################################################################################
  justin-court-list-api:
    container_name: justin-court-list-api
    hostname: justin-court-list-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_TESTS=true
    ports:
      - "8083:8080"
    environment:
      - COURTLIST_BASEURL=null
      - COURTLIST_USERNAME=null
      - COURTLIST_PASSWORD=null
      - ISSUER_URI=null
      - RESOURCE_ID=null
      - PRINCIPLE_ATTRIBUTE=null
