version: "3.7"
services:

  #############################################################################################
  ###                           Document Distribution Webservice                            ###
  #############################################################################################
  justin-court-list-api:
    container_name: justin-court-list-api
    hostname: justin-court-list-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SKIP_TESTS=true
    ports:
      - "8099:8080"
    environment:
      - COURTLIST_BASEURL=${COURTLIST_BASEURL}
      - COURTLIST_USERNAME=${COURTLIST_USERNAME}
      - COURTLIST_PASSWORD=${COURTLIST_PASSWORD}
      - ISSUER_URI=${ISSUER_URI}
      - RESOURCE_ID=${RESOURCE_ID}
      - PRINCIPLE_ATTRIBUTE=${PRINCIPLE_ATTRIBUTE}
      - PORT=${PORT}

