---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: court-list-ws
spec:
  selector:
    matchLabels:
      app: court-list-ws
  replicas: 1
  template:
    metadata:
      labels:
        app: court-list-ws
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      containers:
        - name: court-list-ws
          image: >-
            image-registry.openshift-image-registry.svc:5000/wuboml-tools/court-list-ws:dev
          ports:
            - name: app
              containerPort: 8083
          envFrom:
            - configMapRef:
                name: court-list-ws-config
            - secretRef:
                name: court-list-ws-secret
# TODO - setup the liveness and readiness probes
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: app
#              scheme: HTTP
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: app
#              scheme: HTTP
          startupProbe:
            tcpSocket:
              port: app
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10