apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

generatorOptions:
  labels:
    app: court-list-ws

images:
  - name: "image-registry.openshift-image-registry.svc:5000/wuboml-tools/court-list-ws"
    newTag: "latest"
