server:
  port: ${PORT:8083}
  servlet:
    context-path: "/courtlist"

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9999}

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#Justin courtlist data properties
courtlist:
  base-url: ${COURTLIST_BASEURL}
  username: ${COURTLIST_USERNAME}
  password: ${COURTLIST_PASSWORD}
  data-extract-uri: "/courtlisttoxml?pApprStartDate=%s&pApprEndDate=%s"
  data-buffer-size: ${COURTLIST_DATA_BUFFER:160}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE:justin-courtlist-api}
  use-resource-role-mappings: true
  bearer-only: true
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
