server:
  port: ${PORT:8083}
  servlet:
    context-path: "/courtlist"

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9999}

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:https://localhost:8081/auth/realms/isb-api}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
courtlist:
  base-url: ${COURTLIST_BASEURL}
  username: ${COURTLIST_USERNAME}
  password: ${COURTLIST_PASSWORD}
  data-extract-uri: "/courtlisttoxml?pApprStartDate=%s&pApprEndDate=%s"
  data-buffer-size: ${COURTLIST_DATA_BUFFER:160}

jwt:
  auth:
    converter:
      resource-id: ${RESOURCE_ID:justin-courtlist-api}
      principle-attribute: ${PRINCIPLE_ATTRIBUTE:preferred_username}
